### ISSUE TITLE
Enhance PhoneMask to Support International Numbers

### ISSUE THREAD

**Issue by ozkary** [ozkary/UISpark#1]
## Enhancement Proposal: Support for International Phone Numbers

**Component**: PhoneMask

### Current Behavior
The current implementation of PhoneMask formats phone numbers in the format `xxx-xxx-xxxx`. This does not support international phone number formats which can vary widely.

### Expected Behavior
Enhance the PhoneMask component to support international phone number formats, such as `1-111-222-3333`, `+44 20 7123 4567`, etc.

### Suggested Approach
1. Detect the country code and format the number accordingly.
2. Use a library or implement logic to handle different international formats.

### Additional Context
This enhancement will make PhoneMask more versatile and applicable in a global context.

**Label**: enhancement

**Comment by gitdevjin** [comment]
I would like to try this :)

**Comment by gitdevjin** [comment]
@ozkary  Okay! I will reopen it
